# Site settings
title: Web动画性能指南
description: "Animation performance guide book for the (mobile) web"
email: lee.alexorz@gmail.com
username: Alexius Lee
baseurl: ""
url: "https://github.com/alexorz"

# Build settings
markdown: kramdown
permalink: pretty
